[package]
name = "dz_validator_pda"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-sdk = "3.0.0"
solana-client = "3.0.2"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
bs58 = "0.5"
solana-system-interface = "2.0.0"

[lib]
name = "dz_validator_pda"
path = "src/main.rs"
